# Generated by Django 2.2.28 on 2023-07-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangomain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_register',
            name='expiry_date',
            field=models.CharField(max_length=200),
        ),
    ]
