# Generated by Django 2.2.28 on 2023-07-20 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangomain', '0005_auto_20230720_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine_register',
            old_name='name',
            new_name='mname',
        ),
    ]
