# Generated by Django 2.2.28 on 2023-07-21 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangomain', '0006_auto_20230720_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine_register',
            old_name='mname',
            new_name='name',
        ),
    ]
